substitutions:
  _REGION: asia-southeast1
  _SERVICE: ho-so-bds
  _REPOSITORY: ho-so-bds
  _IMAGE_TAG: latest
  _NEXT_PUBLIC_APP_MODE: demo
  _NEXT_PUBLIC_SITE_URL: ""
  _NEXT_PUBLIC_SUPABASE_URL: ""
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ""

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_APP_MODE=${_NEXT_PUBLIC_APP_MODE}
      - --build-arg
      - NEXT_PUBLIC_SITE_URL=${_NEXT_PUBLIC_SITE_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8080"
      - --memory
      - 512Mi
      - --cpu
      - "1"
      - --min-instances
      - "0"
      - --max-instances
      - "3"

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_IMAGE_TAG}
